## CAN NOT CHANGE STRUCTURE OF A TFLITE MODEL.
## TRAIN MODEL IN H5 OR PB FORMAT -> CHANGE ITS STRUCTURE -> CONVERT TO TFLITE
## https://colab.research.google.com/drive/1s1lkOiqKgl9_MsXJtPF--oh6uXHYkNYm